name       : hunspell-id
version    : 2.1
release    : 2
source     :
    - https://github.com/shuLhan/hunspell-id/archive/v2.1.tar.gz : 3afdd87a1fb6951c67d40d79fdca018bce850cd395f0d74d62fe4f27f371ef64
license    : LGPL-3.0-only
component  : office.spelling
summary    : Indonesian hunspell dictionary
description: |
    This is Bahasa Indonesia dictionary for hunspell
rundeps  :
    - libhunspell
install    : |
    install -Dm00644 id_ID.aff $installdir/usr/share/hunspell/id_ID.aff
    install -Dm00644 id_ID.dic $installdir/usr/share/hunspell/id_ID.dic
